@api = https://localhost:7146

GET {{api}}/weatherforecast/
Accept: application/json

### CompanyController
GET {{api}}/api/Company/
Accept: application/json
###
GET {{api}}/api/Company/30933806-3C8A-4199-2649-08DE31E1D5B4
Accept: application/json
###
POST {{api}}/api/Company
Content-Type: application/json

{
  "Name":"Testowa firma",
  "AddressCompany": 
  {
    "Street":"Testowa ulica",
    "BuildingNumber":"21",
    "PostalCode":"30-100",
    "City":"Rzeszów"
  }
}
###
PUT {{api}}/api/Company/D0EC56E5-8497-4894-4D3C-08DE2D3CC3F3
Content-Type: application/json

{
  "Name":"Firma do testowania",
  "AddressCompany":
  {
    "Street":"Testowa ulicaXSD",
    "BuildingNumber":"21",
    "PostalCode":"30-100",
    "City":"Rzeszów"
  }
}

###
DELETE {{api}}/api/Company/4C139D0F-FCE3-44CA-1330-08DE31DDBABD

### DepartmentController
GET {{api}}/api/Department/
Accept: application/json

###
GET {{api}}/api/Department/ADCA22F8-0AE1-439C-D972-08DE31E59924
Accept: application/json

###
POST {{api}}/api/Department/30933806-3c8a-4199-2649-08de31e1d5b4
Content-Type: application/json

{
  "Name":"Firma do testowania22",
  "Description": "Test opisu222",
  "AddressDepartment":
  {
    "Street":"Testowa ulicaXS2222222D",
    "BuildingNumber":"21231",
    "PostalCode":"30-100",
    "City":"Rzeszówff"
  }
}

###
PUT {{api}}/api/Department/ADCA22F8-0AE1-439C-D972-08DE31E59924
Content-Type: application/json

{
  "Name":"Firma do testowania aktualizowana",
  "Description": "Test opisu aktualizowany",
  "AddressDepartment":
  {
    "Street":"Testowa ulica",
    "BuildingNumber":"22",
    "PostalCode":"30-100",
    "City":"Rzeszówfw"
  }
}

###
DELETE {{api}}/api/Department/8B1352F0-8CDA-4A64-2C1A-08DE31E5F2D5

### Wardrobe
GET {{api}}/api/Wardrobe
Accept: application/json

###
GET {{api}}/api/Wardrobe/72a841c2-d44a-429d-9fc3-d943850e11f2
Accept: application/json

###
POST {{api}}/api/Wardrobe/company/30933806-3C8A-4199-2649-08DE31E1D5B4/department/ADCA22F8-0AE1-439C-D972-08DE31E59924
Content-Type: application/json

{
  "Name": "Testowa szafa",
  "Model": "Test",
  "SerialNumber": "321D321",
  "SoftwareVersion": "321"
}

###
POST {{api}}/api/Wardrobe/company/30933806-3C8A-4199-2649-08DE31E1D5B4
Content-Type: application/json

{
  "Name": "Testowa szafa dla Firmy",
  "Model": "Test",
  "SerialNumber": "321D321",
  "SoftwareVersion": "321"
}

###
POST {{api}}/api/Wardrobe/department/ADCA22F8-0AE1-439C-D972-08DE31E59924
Content-Type: application/json

{
  "Name": "Testowa szafa dla oddziału",
  "Model": "Test",
  "SerialNumber": "321D321",
  "SoftwareVersion": "321"
}

###
PUT {{api}}/api/Wardrobe/A041EB4F-0D6A-436A-1EC4-08DE3374EF5C
Content-Type: application/json

{
  "Name": "Testowa szafa",
  "Model": "Test",
  "SerialNumber": "321D321",
  "SoftwareVersion": "321"
}

###
DELETE {{api}}/api/Wardrobe/BAE154BC-7CA8-4379-C5F9-08DE3378D21F
