@api = https://localhost:7146

GET {{api}}/weatherforecast/
Accept: application/json

### CompanyController
GET {{api}}/api/Company/
Accept: application/json
###
GET {{api}}/api/Company/53d7c4f2-8e80-4712-a0ce-207163cc88da
Accept: application/json
###
POST {{api}}/api/Company
Content-Type: application/json

{
  "Name":"Testowa firma",
  "AddressCompany": 
  {
    "Street":"Testowa ulica",
    "BuildingNumber":"21",
    "PostalCode":"30-100",
    "City":"Rzeszów"
  }
}
###
PUT {{api}}/api/Company/D0EC56E5-8497-4894-4D3C-08DE2D3CC3F3
Content-Type: application/json

{
  "Name":"Firma do testowania",
  "AddressCompany":
  {
    "Street":"Testowa ulicaXSD",
    "BuildingNumber":"21",
    "PostalCode":"30-100",
    "City":"Rzeszów"
  }
}

###
DELETE {{api}}/api/Company/D0EC56E5-8497-4894-4D3C-08DE2D3CC3F3

