@api = https://localhost:7146

GET {{api}}/weatherforecast/
Accept: application/json

### CompanyController
GET {{api}}/api/Company/
Accept: application/json
###
GET {{api}}/api/Company/30933806-3C8A-4199-2649-08DE31E1D5B4
Accept: application/json
###
POST {{api}}/api/Company
Content-Type: application/json

{
  "Name":"Testowa firma",
  "AddressCompany": 
  {
    "Street":"Testowa ulica",
    "BuildingNumber":"21",
    "PostalCode":"30-100",
    "City":"Rzeszów"
  }
}
###
PUT {{api}}/api/Company/D0EC56E5-8497-4894-4D3C-08DE2D3CC3F3
Content-Type: application/json

{
  "Name":"Firma do testowania",
  "AddressCompany":
  {
    "Street":"Testowa ulicaXSD",
    "BuildingNumber":"21",
    "PostalCode":"30-100",
    "City":"Rzeszów"
  }
}

###
DELETE {{api}}/api/Company/4C139D0F-FCE3-44CA-1330-08DE31DDBABD

### DepartmentController
GET {{api}}/api/Department/
Accept: application/json

###
GET {{api}}/api/Department/ADCA22F8-0AE1-439C-D972-08DE31E59924
Accept: application/json

###
POST {{api}}/api/Department/30933806-3c8a-4199-2649-08de31e1d5b4
Content-Type: application/json

{
  "Name":"Firma do testowania22",
  "Description": "Test opisu222",
  "AddressDepartment":
  {
    "Street":"Testowa ulicaXS2222222D",
    "BuildingNumber":"21231",
    "PostalCode":"30-100",
    "City":"Rzeszówff"
  }
}

###
PUT {{api}}/api/Department/ADCA22F8-0AE1-439C-D972-08DE31E59924
Content-Type: application/json

{
  "Name":"Firma do testowania aktualizowana",
  "Description": "Test opisu aktualizowany",
  "AddressDepartment":
  {
    "Street":"Testowa ulica",
    "BuildingNumber":"22",
    "PostalCode":"30-100",
    "City":"Rzeszówfw"
  }
}

###
DELETE {{api}}/api/Department/8B1352F0-8CDA-4A64-2C1A-08DE31E5F2D5

### Wardrobe
GET {{api}}/api/Wardrobe
Accept: application/json

###
GET {{api}}/api/Wardrobe/72a841c2-d44a-429d-9fc3-d943850e11f2
Accept: application/json

###
POST {{api}}/api/Wardrobe/company/30933806-3C8A-4199-2649-08DE31E1D5B4/department/ADCA22F8-0AE1-439C-D972-08DE31E59924
Content-Type: application/json

{
  "Name": "Testowa szafa",
  "Model": "Test",
  "SerialNumber": "321D321",
  "SoftwareVersion": "321"
}

###
POST {{api}}/api/Wardrobe/company/30933806-3C8A-4199-2649-08DE31E1D5B4
Content-Type: application/json

{
  "Name": "Testowa szafa dla Firmy",
  "Model": "Test",
  "SerialNumber": "321D321",
  "SoftwareVersion": "321"
}

###
POST {{api}}/api/Wardrobe/department/ADCA22F8-0AE1-439C-D972-08DE31E59924
Content-Type: application/json

{
  "Name": "Testowa szafa dla oddziału",
  "Model": "Test",
  "SerialNumber": "321D321",
  "SoftwareVersion": "321"
}

###
PUT {{api}}/api/Wardrobe/A041EB4F-0D6A-436A-1EC4-08DE3374EF5C
Content-Type: application/json

{
  "Name": "Testowa szafa",
  "Model": "Test",
  "SerialNumber": "321D321",
  "SoftwareVersion": "321"
}

###
DELETE {{api}}/api/Wardrobe/BAE154BC-7CA8-4379-C5F9-08DE3378D21F

###
GET {{api}}/api/Drawer/Wardrobe/A041EB4F-0D6A-436A-1EC4-08DE3374EF5C
Accept: application/json

###
GET {{api}}/api/Drawer/A1576BC2-E2A7-47FE-A4E8-08DE345963B7
Accept: application/json

### 
POST {{api}}/api/Drawer/A041EB4F-0D6A-436A-1EC4-08DE3374EF5C
Content-Type: application/json

{
  "Name": "A01",
  "x": 1,
  "Y": 1,
  "Z": 10,
  "Width": 20,
  "Height": 30
}

### 
PUT {{api}}/api/Drawer/A1576BC2-E2A7-47FE-A4E8-08DE345963B7
Content-Type: application/json

{
  "Name": "Szuflada - A01",
  "x": 0,
  "Y": 0,
  "Z": 10,
  "Width": 30,
  "Height": 30
}

###
DELETE {{api}}/api/Drawer/A1576BC2-E2A7-47FE-A4E8-08DE345963B7

### Item

GET {{api}}/api/Item
Accept: application/json

### 
POST {{api}}/api/Item/FB02B11D-4304-46A1-A4E9-08DE345963B7
Content-Type: application/json

{
  "Name":"Testowy przedmiot",
  "Description": "Testowy opis",
  "Status": "Dostępny",
  "Quantity": 10,
  "Partition": 2
}

### 
PUT {{api}}/api/Item/cfd84807-1f08-4ebe-e8b2-08de35007339
Content-Type: application/json

{
  "Name":"Testowy przedmiot aktualizacja",
  "Description": "Testowy opis aktualizacja",
  "Status": "Dostępny",
  "Quantity": 10,
  "Partition": 2
}

###
DELETE {{api}}/api/Item/cfd84807-1f08-4ebe-e8b2-08de35007339


### Auth

POST {{api}}/api/Auth/register
Content-Type: application/json

{
  "Email": "admin@gmail.com",
  "Username": "admin",
  "Password": "Admin123",
  "FirstName": "Jan",
  "LastName": "Kowalski"
}

###
POST {{api}}/api/Auth/login
Content-Type: application/json

{
  "Username": "admin",
  "Password": "Admin123"
}

### User

GET {{api}}/api/User/3f788849-5e59-4690-c7de-08de3c1c6174
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjNmNzg4ODQ5LTVlNTktNDY5MC1jN2RlLTA4ZGUzYzFjNjE3NCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE3NjU4Mzk1MzksImlzcyI6IkludmVuVHJhY2tlciIsImF1ZCI6IkludmVuVHJhY2tlclVzZXJzIn0.46NedftGnYs4_eGDB8lLCykmGXf5DZFnO6s0b61TMRQ

###

GET {{api}}/api/User/me
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjNmNzg4ODQ5LTVlNTktNDY5MC1jN2RlLTA4ZGUzYzFjNjE3NCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE3NjU4Mzk1MzksImlzcyI6IkludmVuVHJhY2tlciIsImF1ZCI6IkludmVuVHJhY2tlclVzZXJzIn0.46NedftGnYs4_eGDB8lLCykmGXf5DZFnO6s0b61TMRQ
