// <auto-generated />
using System;
using InvenTracker.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvenTracker.Infrastructure.Migrations
{
    [DbContext(typeof(InvenTrackerDbContext))]
    [Migration("20260302182517_UpdateName")]
    partial class UpdateName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvenTracker.Domain.Entities.AddressCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("AddressCompanies");
                });

            modelBuilder.Entity("InvenTracker.Domain.Entities.AddressDepartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .IsUnique();

                    b.ToTable("AddressDepartments");
                });

            modelBuilder.Entity("InvenTracker.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("InvenTracker.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("InvenTracker.Domain.Entities.Drawer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AvailablePartitions")
                        .HasColumnType("int");

                    b.Property<int>("HeightDrawer")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentDrawerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TotalPartitions")
                        .HasColumnType("int");

                    b.Property<Guid?>("WardrobeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WidthDrawer")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentDrawerId");

                    b.HasIndex("WardrobeId");

                    b.ToTable("Drawers");
                });

            modelBuilder.Entity("InvenTracker.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PartitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PartitionId")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("InvenTracker.Domain.Entities.Partition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DrawerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HeightPartition")
                        .HasColumnType("int");

                    b.Property<int>("WidthPartition")
                        .HasColumnType("int");

                    b.Property<int>("Z")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DrawerId");

                    b.ToTable("Partitions");
                });

            modelBuilder.Entity("InvenTracker.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("InvenTracker.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InvenTracker.Domain.Entities.Wardrobe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoftwareVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Wardrobes");
                });

            modelBuilder.Entity("InvenTracker.Domain.Entities.AddressCompany", b =>
                {
                    b.HasOne("InvenTracker.Domain.Entities.Company", "Company")
                        .WithOne("Address")
                        .HasForeignKey("InvenTracker.Domain.Entities.AddressCompany", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("InvenTracker.Domain.Entities.AddressDepartment", b =>
                {
                    b.HasOne("InvenTracker.Domain.Entities.Department", "Department")
                        .WithOne("Address")
                        .HasForeignKey("InvenTracker.Domain.Entities.AddressDepartment", "DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("InvenTracker.Domain.Entities.Department", b =>
                {
                    b.HasOne("InvenTracker.Domain.Entities.Company", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("InvenTracker.Domain.Entities.Drawer", b =>
                {
                    b.HasOne("InvenTracker.Domain.Entities.Drawer", "ParentDrawer")
                        .WithMany("SubDrawers")
                        .HasForeignKey("ParentDrawerId");

                    b.HasOne("InvenTracker.Domain.Entities.Wardrobe", "Wardrobe")
                        .WithMany("Drawers")
                        .HasForeignKey("WardrobeId");

                    b.Navigation("ParentDrawer");

                    b.Navigation("Wardrobe");
                });

            modelBuilder.Entity("InvenTracker.Domain.Entities.Item", b =>
                {
                    b.HasOne("InvenTracker.Domain.Entities.Partition", "Partition")
                        .WithOne("Item")
                        .HasForeignKey("InvenTracker.Domain.Entities.Item", "PartitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partition");
                });

            modelBuilder.Entity("InvenTracker.Domain.Entities.Partition", b =>
                {
                    b.HasOne("InvenTracker.Domain.Entities.Drawer", "Drawer")
                        .WithMany("Partitions")
                        .HasForeignKey("DrawerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drawer");
                });

            modelBuilder.Entity("InvenTracker.Domain.Entities.User", b =>
                {
                    b.HasOne("InvenTracker.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("InvenTracker.Domain.Entities.Wardrobe", b =>
                {
                    b.HasOne("InvenTracker.Domain.Entities.Company", "Company")
                        .WithMany("Wardrobes")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("InvenTracker.Domain.Entities.Department", "Department")
                        .WithMany("Wardrobes")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("InvenTracker.Domain.Entities.Company", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Departments");

                    b.Navigation("Wardrobes");
                });

            modelBuilder.Entity("InvenTracker.Domain.Entities.Department", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Wardrobes");
                });

            modelBuilder.Entity("InvenTracker.Domain.Entities.Drawer", b =>
                {
                    b.Navigation("Partitions");

                    b.Navigation("SubDrawers");
                });

            modelBuilder.Entity("InvenTracker.Domain.Entities.Partition", b =>
                {
                    b.Navigation("Item");
                });

            modelBuilder.Entity("InvenTracker.Domain.Entities.Wardrobe", b =>
                {
                    b.Navigation("Drawers");
                });
#pragma warning restore 612, 618
        }
    }
}
